# Site settings
title: DHAVAL PATEL
email: dhavalptl319@gmail.com
description: "Step into my data analyst portfolio—an exploration of insights and strategic data narratives, shaping informed business choices."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

#twitter_username:
github_username: DhavalPatel511

# Build settings
markdown: kramdown
